# Generated by Django 4.2 on 2023-08-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название альбома', max_length=150, unique=True, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(help_text='Год альбома', verbose_name='Год')),
                ('singer', models.ForeignKey(help_text='Исполнитель', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.singer', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ('name',),
            },
        ),
    ]
