# Generated by Django 4.2 on 2023-08-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название песни', max_length=250, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Год альбома', verbose_name='Год')),
                ('album', models.ForeignKey(help_text='Свойства альбома', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.album', verbose_name='Альбом')),
                ('song', models.ForeignKey(help_text='Свойства песни', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='catalog.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня альбома',
                'verbose_name_plural': 'Песни альбома',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(help_text='Песня альбома', through='catalog.AlbumSong', to='catalog.song', verbose_name='Песня'),
        ),
    ]
