# Generated by Django 4.2 on 2023-08-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_song_albumsong_album_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsong',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Номер песни в альбоме', verbose_name='Номер'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='unique_album_song'),
        ),
    ]
